### ISSUE TITLE
NoClassDefFound when launching App

### ISSUE THREAD

**Issue by mbackermann** [h4nyu/react-native-zebra-rfid#2]
When I try to run it on my emulator, the app crashes immediately. The error message that I can see on logcat is:

```
07-17 09:01:28.281  5557  5601 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.zebra.rfid.api3.Readers.a(SourceFile:53)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.zebra.rfid.api3.Readers.<init>(SourceFile:68)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.rnzebrarfid.RNZebraRfidModule.<init>(RNZebraRfidModule.java:62)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.rnzebrarfid.RNZebraRfidPackage.createNativeModules(RNZebraRfidPackage.java:17)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/~~BeMQmOwUej_f8Mb9eAnBQA==/com.test_rfid-ErGXVsXgnhncl--biDLU4A==/base.apk"],nativeLibraryDirectories=[/data/app/~~BeMQmOwUej_f8Mb9eAnBQA==/com.test_rfid-ErGXVsXgnhncl--biDLU4A==/lib/x86, /data/app/~~BeMQmOwUej_f8Mb9eAnBQA==/com.test_rfid-ErGXVsXgnhncl--biDLU4A==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-17 09:01:28.281  5557  5601 E AndroidRuntime: 	... 12 more
07-17 09:01:28.288   583  5602 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-17 09:01:28.288   583   910 W ActivityTaskManager:   Force finishing activity com.test_rfid/.MainActivity
```

**Comment by h4nyu** [comment]
Try [latest version](https://www.npmjs.com/package/@oniku/react-native-zebra-rfid).
